### ISSUE TITLE
how to build clock2

### ISSUE THREAD

**Issue by KeLaiFu** [Fihdi/Eurorack#2]
your new clock module looks very interesting but looking at the kicad files, I am not sure how it is assembled. Could you add some pictures of the finished module?

**Comment by Fihdi** [comment]
Yea sure, it requires some jumper wires. I will upload the pictures when I come to it, because I have not built this module yet.

**Comment by KeLaiFu** [comment]
nice one! I'm not in a rush but looking forward to seeing it in action. Thanks for your great work.

**Comment by Fihdi** [comment]
Done! Check the build guide pdf within the ClockDivider2 folder ;)
